CREATE TABLE public.level_up_thresholds (
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    level_id bigint NOT NULL,
    listening_hours_threshold integer NOT NULL DEFAULT 0,
    video_hours_threshold integer NOT NULL DEFAULT 0,
    book_count_threshold integer NOT NULL DEFAULT 0,
    activity_count_threshold integer NOT NULL DEFAULT 0,
    pass_condition text,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    updated_at timestamp with time zone NOT NULL DEFAULT now(),
    CONSTRAINT level_up_thresholds_pkey PRIMARY KEY (id),
    CONSTRAINT level_up_thresholds_level_id_key UNIQUE (level_id),
    CONSTRAINT level_up_thresholds_level_id_fkey FOREIGN KEY (level_id) REFERENCES public.levels(id) ON DELETE CASCADE
);

COMMENT ON TABLE public.level_up_thresholds IS '각 레벨을 통과(레벨업)하기 위해 필요한 누적 활동량 기준을 정의하는 테이블';
COMMENT ON COLUMN public.level_up_thresholds.level_id IS '기준이 적용되는 레벨 ID';
COMMENT ON COLUMN public.level_up_thresholds.listening_hours_threshold IS '목표 누적 흘려듣기 시간';
COMMENT ON COLUMN public.level_up_thresholds.video_hours_threshold IS '목표 누적 영상 노출 시간';
COMMENT ON COLUMN public.level_up_thresholds.book_count_threshold IS '목표 누적 책 읽기 권수';
COMMENT ON COLUMN public.level_up_thresholds.activity_count_threshold IS '목표 누적 독후 활동 횟수';
COMMENT ON COLUMN public.level_up_thresholds.pass_condition IS '통과를 위한 정성적 조건 설명 (엄마 확인용)';
